name: Check Branch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Check-Branch:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Ruby dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - name: Debug Environment
        run: |
          echo "Ruby version: $(ruby -v)"
          echo "Bundler version: $(bundle -v)"

      - name: Ensure required gems are installed
        run: bundle install

      - name: Run CI pipeline for the gem
        run: bin/check

      - name: Collect Brakeman warnings (Optional)
        if: always()
        run: |
          mkdir -p reports
          bin/check > reports/brakeman.log || true
        continue-on-error: true
